"""Pydantic schemas for API request/response validation."""

from app.schemas.auth import Token, TokenPayload, LoginRequest
from app.schemas.user import UserCreate, UserUpdate, UserResponse
from app.schemas.supplier import SupplierCreate, SupplierUpdate, SupplierResponse
from app.schemas.product import ProductCreate, ProductUpdate, ProductResponse, ProductImportRow
from app.schemas.location import LocationCreate, LocationUpdate, LocationResponse
from app.schemas.stock import StockOnHandResponse, StockMovementResponse
from app.schemas.inventory import (
    InventorySessionCreate,
    InventorySessionResponse,
    InventoryLineCreate,
    InventoryLineResponse,
)
from app.schemas.order import (
    PurchaseOrderCreate,
    PurchaseOrderResponse,
    PurchaseOrderLineCreate,
    PurchaseOrderLineResponse,
    OrderSuggestion,
)
from app.schemas.pos import PosSalesLineResponse, PosImportResult
from app.schemas.recipe import RecipeCreate, RecipeUpdate, RecipeResponse, RecipeLineCreate
from app.schemas.ai import ShelfScanRequest, ShelfScanResponse, Detection
from app.schemas.sync import SyncPullResponse, SyncPushRequest
from app.schemas.reconciliation import (
    ReconciliationResultResponse,
    ReconciliationSummary,
    ReorderProposalResponse,
    ReorderProposalUpdate,
    ReorderSummary,
    SupplierOrderDraftResponse,
    SupplierOrderDraftDetail,
    SupplierOrderDraftUpdate,
    ReconcileRequest,
    GenerateReordersRequest,
    GenerateOrderDraftsRequest,
    ExportOrderRequest,
    ExportOrderResponse,
    EmailTemplateResponse,
    DeltaSeverity,
    OrderDraftStatus,
)

# Invoice OCR & AP Automation
from app.schemas.invoice import (
    InvoiceCreate,
    InvoiceUpdate,
    InvoiceResponse,
    InvoiceLineCreate,
    InvoiceLineResponse,
    InvoiceOCRRequest,
    InvoiceOCRResponse,
    PriceHistoryResponse,
    PriceAlertResponse,
    PriceTrendResponse,
    GLCodeCreate,
    GLCodeResponse,
    APApprovalCreate,
    APApprovalResponse,
    APApprovalAction,
)

# Marketing Automation
from app.schemas.marketing import (
    CampaignCreate,
    CampaignUpdate,
    CampaignResponse,
    CampaignStats,
    CampaignRecipientResponse,
    SegmentCreate,
    SegmentUpdate,
    SegmentResponse,
    SegmentPreview,
    TriggerCreate,
    TriggerUpdate,
    TriggerResponse,
    MenuRecommendationResponse,
    CustomerRecommendations,
    LoyaltyProgramCreate,
    LoyaltyProgramResponse,
    CustomerLoyaltyResponse,
    LoyaltyTransaction,
    LoyaltyRedemption,
    LoyaltyRedemptionResponse,
    AICampaignRequest,
    AICampaignResponse,
)

# Reservations & Waitlist
from app.schemas.reservations import (
    ReservationCreate,
    ReservationUpdate,
    ReservationResponse,
    ReservationCalendar,
    AvailabilityRequest,
    AvailabilityResponse,
    WaitlistCreate,
    WaitlistUpdate,
    WaitlistResponse,
    WaitlistNotification,
    TableAvailabilityResponse,
    TableBlockRequest,
    ReservationSettingsCreate,
    ReservationSettingsResponse,
    GuestHistoryResponse,
    GuestNotesUpdate,
    SMSTemplateResponse,
    SMSPreview,
)

# Delivery Aggregator
from app.schemas.delivery import (
    DeliveryIntegrationCreate,
    DeliveryIntegrationUpdate,
    DeliveryIntegrationResponse,
    DeliveryOrderResponse,
    DeliveryOrderItemResponse,
    DeliveryOrderStatusUpdate,
    DeliveryOrderAccept,
    DeliveryOrderReject,
    MenuSyncResponse,
    MenuSyncRequest,
    ItemAvailabilityUpdate,
    ItemAvailabilityResponse,
    BulkAvailabilityUpdate,
    PlatformMappingCreate,
    PlatformMappingResponse,
    WebhookPayload,
    WebhookResponse,
    DeliverySummary,
    DeliveryPerformance,
    PlatformComparison,
)

# Analytics & AI
from app.schemas.analytics import (
    MenuAnalysisResponse,
    MenuEngineeringReport,
    MenuOptimizationSuggestion,
    ServerPerformanceResponse,
    ServerRanking,
    ServerPerformanceReport,
    SalesForecastResponse,
    ForecastRequest,
    ForecastReport,
    DailyMetricsResponse,
    MetricsTrend,
    ConversationalQueryRequest,
    ConversationalQueryResponse,
    ConversationHistory,
    QueryFeedback,
    BenchmarkResponse,
    BenchmarkComparison,
    PerformanceReport,
    BottleWeightResponse,
    BottleWeightCreate,
    ScaleReadingRequest,
    ScaleReadingResponse,
    VisualEstimateRequest,
    InventoryCountRequest,
    InventoryCountResponse,
)

__all__ = [
    # Auth
    "Token",
    "TokenPayload",
    "LoginRequest",
    # User
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    # Supplier
    "SupplierCreate",
    "SupplierUpdate",
    "SupplierResponse",
    # Product
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "ProductImportRow",
    # Location
    "LocationCreate",
    "LocationUpdate",
    "LocationResponse",
    # Stock
    "StockOnHandResponse",
    "StockMovementResponse",
    # Inventory
    "InventorySessionCreate",
    "InventorySessionResponse",
    "InventoryLineCreate",
    "InventoryLineResponse",
    # Order
    "PurchaseOrderCreate",
    "PurchaseOrderResponse",
    "PurchaseOrderLineCreate",
    "PurchaseOrderLineResponse",
    "OrderSuggestion",
    # POS
    "PosSalesLineResponse",
    "PosImportResult",
    # Recipe
    "RecipeCreate",
    "RecipeUpdate",
    "RecipeResponse",
    "RecipeLineCreate",
    # AI
    "ShelfScanRequest",
    "ShelfScanResponse",
    "Detection",
    # Sync
    "SyncPullResponse",
    "SyncPushRequest",
    # Reconciliation
    "ReconciliationResultResponse",
    "ReconciliationSummary",
    "ReorderProposalResponse",
    "ReorderProposalUpdate",
    "ReorderSummary",
    "SupplierOrderDraftResponse",
    "SupplierOrderDraftDetail",
    "SupplierOrderDraftUpdate",
    "ReconcileRequest",
    "GenerateReordersRequest",
    "GenerateOrderDraftsRequest",
    "ExportOrderRequest",
    "ExportOrderResponse",
    "EmailTemplateResponse",
    "DeltaSeverity",
    "OrderDraftStatus",
    # Invoice OCR & AP
    "InvoiceCreate",
    "InvoiceUpdate",
    "InvoiceResponse",
    "InvoiceLineCreate",
    "InvoiceLineResponse",
    "InvoiceOCRRequest",
    "InvoiceOCRResponse",
    "PriceHistoryResponse",
    "PriceAlertResponse",
    "PriceTrendResponse",
    "GLCodeCreate",
    "GLCodeResponse",
    "APApprovalCreate",
    "APApprovalResponse",
    "APApprovalAction",
    # Marketing
    "CampaignCreate",
    "CampaignUpdate",
    "CampaignResponse",
    "CampaignStats",
    "CampaignRecipientResponse",
    "SegmentCreate",
    "SegmentUpdate",
    "SegmentResponse",
    "SegmentPreview",
    "TriggerCreate",
    "TriggerUpdate",
    "TriggerResponse",
    "MenuRecommendationResponse",
    "CustomerRecommendations",
    "LoyaltyProgramCreate",
    "LoyaltyProgramResponse",
    "CustomerLoyaltyResponse",
    "LoyaltyTransaction",
    "LoyaltyRedemption",
    "LoyaltyRedemptionResponse",
    "AICampaignRequest",
    "AICampaignResponse",
    # Reservations
    "ReservationCreate",
    "ReservationUpdate",
    "ReservationResponse",
    "ReservationCalendar",
    "AvailabilityRequest",
    "AvailabilityResponse",
    "WaitlistCreate",
    "WaitlistUpdate",
    "WaitlistResponse",
    "WaitlistNotification",
    "TableAvailabilityResponse",
    "TableBlockRequest",
    "ReservationSettingsCreate",
    "ReservationSettingsResponse",
    "GuestHistoryResponse",
    "GuestNotesUpdate",
    "SMSTemplateResponse",
    "SMSPreview",
    # Delivery
    "DeliveryIntegrationCreate",
    "DeliveryIntegrationUpdate",
    "DeliveryIntegrationResponse",
    "DeliveryOrderResponse",
    "DeliveryOrderItemResponse",
    "DeliveryOrderStatusUpdate",
    "DeliveryOrderAccept",
    "DeliveryOrderReject",
    "MenuSyncResponse",
    "MenuSyncRequest",
    "ItemAvailabilityUpdate",
    "ItemAvailabilityResponse",
    "BulkAvailabilityUpdate",
    "PlatformMappingCreate",
    "PlatformMappingResponse",
    "WebhookPayload",
    "WebhookResponse",
    "DeliverySummary",
    "DeliveryPerformance",
    "PlatformComparison",
    # Analytics
    "MenuAnalysisResponse",
    "MenuEngineeringReport",
    "MenuOptimizationSuggestion",
    "ServerPerformanceResponse",
    "ServerRanking",
    "ServerPerformanceReport",
    "SalesForecastResponse",
    "ForecastRequest",
    "ForecastReport",
    "DailyMetricsResponse",
    "MetricsTrend",
    "ConversationalQueryRequest",
    "ConversationalQueryResponse",
    "ConversationHistory",
    "QueryFeedback",
    "BenchmarkResponse",
    "BenchmarkComparison",
    "PerformanceReport",
    "BottleWeightResponse",
    "BottleWeightCreate",
    "ScaleReadingRequest",
    "ScaleReadingResponse",
    "VisualEstimateRequest",
    "InventoryCountRequest",
    "InventoryCountResponse",
]
